server:
  port: 8092
  address: 0.0.0.0

spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://8.130.66.80:3306/ras_resume?useSSL=false&amp&serverTimezone=UTC
      username: root
      password: 123987
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500


mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    ccw.serviceinnovation.oss.mapper: info

dubbo:
  consumer:
    timeout: 30000
    retries: 0
  protocol:
    id: dubbo
    name: dubbo
    port: -1

  scan:
    basePackages: ccw.ruan.resume
  application:
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
      #可选值 interface、instance、all，默认是 interface，即只注册接口级地址
      #    register-mode: all
      #只消费应用级
      #    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
    # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
    #      migration: APPLICATION_FIRST
    name: yunJian-resume-consumer
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

rocketmq:
  addr: 127.0.0.1:9876
resume:
  path: E:\resume\

