server:
  port: 5555
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  redis:
    host: ${redis.host:127.0.0.1}
    port: ${redis.port:6379}
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: yunJian-job
          uri: lb://yunJian-job #yunJian-job
          predicates:
            - Path=/job/**
        - id: yunJian-resume
          uri: lb://yunJian-resume #yunJian-resume
          predicates:
            - Path=/resume/**
        - id: yunJian-user
          uri: lb://yunJian-user #yunJian-user
          predicates:
            - Path=/user/**
        - id: yunJian-log
          uri: lb://yunJian-user #yunJian-log
          predicates:
            - Path=/log/**
        - id: yunJian-flowPath
          uri: lb://yunJian-user #yunJian-flowPath
          predicates:
            - Path=/flowPath/**
        - id: yunJian-template
          uri: lb://yunJian-user #yunJian-template
          predicates:
            - Path=/template/**
        - id: yunJian-evaluate
          uri: lb://yunJian-user #yunJian-evaluate
          predicates:
            - Path=/evaluate/**

#JWT 双token
jwt:
  accessTokenHeader: ACCESSTOKEN
  refreshTokenHeader: REFRESHTOKEN
  accessTokenExpire: 18000000 #（秒）30分钟
  refreshTokenExpire: 1728000000 #（秒）2天
  secret: abcdefghabcdefghabcdefghabcdefgh
