server:
  port: 5555
  address: 0.0.0.0
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: yunJian-job  #路由的ID，没有固定规则但求唯一，建议配合服务名
          uri: lb://yunJian-job     # 匹配后提供服务的路由地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          predicates:
            - Path=/job/** #断言，路径相匹配的进行路由
        - id: yunJian-resume   #路由的ID，没有固定规则但求唯一，建议配合服务名
          uri: lb://yunJian-resume     # 匹配后提供服务的路由地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          predicates:
            - Path=/resume/** #断言，路径相匹配的进行路由
        - id: yunJian-user   #路由的ID，没有固定规则但求唯一，建议配合服务名
          uri: lb://yunJian-user     # 匹配后提供服务的路由地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          predicates:
            - Path=/user/** #断言，路径相匹配的进行路由