server:
  port: 8083
  address: 0.0.0.0
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql.addr:8.130.66.80:3306}/resume_analysis_system?useSSL=false&amp&serverTimezone=UTC
      username: ${mysql.username:root}
      password: ${mysql.password:123987}
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    ccw.serviceinnovation.oss.mapper: info
dubbo:
  consumer:
    timeout: 30000
    retries: 0
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    basePackages: ccw.ruan.job
  application:
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
    name: yunJian-job-consumer
  registry:
    address: nacos://${nacos.addr:127.0.0.1:8848}
    username: ${nacos.username:nacos}
    password: ${nacos.password:nacos}

py:
  personJob: ${personJob:192.168.50.47:7070}
  jobAnalysis: ${jobAnalysis:192.168.50.159:7071}

